version: "3.6"
services:   
########### Contenido kafka ##########
#Zookeepers
  zoo:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zoo
    ports:
     - 2181:2181
    environment:
     - ZOOKEEPER_SERVER_ID=1
     - ZOOKEEPER_CLIENT_PORT=2181
     - ZOOKEEPER_TICK_TIME=2000
     - ZOOKEEPER_INIT_LIMIT=5
     - ZOOKEEPER_SYNC_LIMIT=2
     - ZOOKEEPER_SERVERS=zoo:2888:3888
#Kafka-clusters
  thor:
    image: confluentinc/cp-kafka:latest
    container_name: thor
    hostname: thor
    ports:
     - 9092:9092
    depends_on:
     - zoo
    environment:
     - KAFKA_BROKER_ID=0
     - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://thor:29092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.41:9092,PLAINTEXT_HOST://thor:29092
     - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
     - KAFKA_ZOOKEEPER_CONNECTION_INTERVAL_MS=6000
     - KAFKA_NUM_PARTITIONS=3
     - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=1
     - KAFKA_AUTO_CREATE_TOPIC_ENABLE=true
     - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
     - KAFKA_DELETE_TOPIC_ENABLE=true
     - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
     - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=2000
   
  captain:
    image: confluentinc/cp-kafka:latest
    container_name: captain
    hostname: captain
    ports:
     - 9094:9094
    depends_on:
     - zoo
    environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://captain:29094
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.41:9094,PLAINTEXT_HOST://captain:29094
     - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
     - KAFKA_ZOOKEEPER_CONNECTION_INTERVAL_MS=6000
     - KAFKA_NUM_PARTITIONS=3
     - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=1   
     - KAFKA_AUTO_CREATE_TOPIC_ENABLE=true
     - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
     - KAFKA_DELETE_TOPIC_ENABLE=true
     - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
     - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=2000
  
  ironman:
    image: confluentinc/cp-kafka:latest
    container_name: ironman
    hostname: ironman
    ports:
     - 9095:9095
    depends_on:
     - zoo
    environment:
     - KAFKA_BROKER_ID=2
     - KAFKA_LISTENERS=PLAINTEXT://:9095,PLAINTEXT_HOST://ironman:29095
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.41:9095,PLAINTEXT_HOST://ironman:29095
     - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
     - KAFKA_ZOOKEEPER_CONNECTION_INTERVAL_MS=6000
     - KAFKA_NUM_PARTITIONS=3
     - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=1   
     - KAFKA_AUTO_CREATE_TOPIC_ENABLE=true
     - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
     - KAFKA_DELETE_TOPIC_ENABLE=true
     - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
     - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=2000
     
########### Contenido mongo ##########
  mongo:
    image: mongo:4.0
    container_name: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: canelita
    #volumes:
      #- "./mongodata:/data/db"      
    ports:
      - "27017:27017"
  mongo-express: 
    image: mongo-express
    #restart: always
    container_name: mongodb-express-ui
    ports:
      - 443:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: canelita
      
########### Contenido mail service ##########
  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP server ports
      - 8025:8025 # Web UI ports     
      
########### Contenido microservicios ##########      
  public-service:
    container_name: public-service
    image: public-service:latest
    environment:
     - KAFKA_HOST_1=thor:29092
     - KAFKA_HOST_2=captain:29094
     - KAFKA_HOST_3=ironman:29095
    depends_on:
     - thor
     - captain
     - ironman
    ports:
        - 8084:8084
  
  subscription-service:
    container_name: subscription-service
    image: subscription-service:latest
    environment:
     - KAFKA_HOST_1=thor:29092
     - KAFKA_HOST_2=captain:29094
     - KAFKA_HOST_3=ironman:29095
     - MONGO_HOST=mongo
    depends_on:
     - thor
     - captain
     - ironman
     - mongo
    ports:
        - 8086:8086
        
  email-service:
    container_name: email-service
    image: email-service:latest
    environment:
     - KAFKA_HOST_1=thor:29092
     - KAFKA_HOST_2=captain:29094
     - KAFKA_HOST_3=ironman:29095
     - MAIL_DEBUG_HOST=mailhog
    depends_on:
     - thor
     - captain
     - ironman
    ports:
        - 8087:8087